### ISSUE TITLE
Snowboy not detecting my wake phrase - could be because audio analyzed in chunks

### ISSUE THREAD

**Issue by troyibm** [Kitt-AI/snowboy#179]
I have a wake phrase (not a single word but two words like "Hey Jackson") and I find that it is really hit or miss with it.  In my testing, I am using the exact recording played from the snowboy web page.  I think it is because the detection is done on a buffer size and if the wake phrase audio splits between buffers, then it won't be detected.  That's my theory on why I will play the same audio over and over and it won't be detected on the first or second try.

I'm building this app using Swift and found that the example in this repo isn't all that helpful.  The https://github.com/grimlockrocks/alexa-swift3-sample-app is a better example since I want to do something with the audio after the wake phrase is detected.

**Comment by troyibm** [comment]
@grimlockrocks you might have some insight into this problem or at least be able to tell me if I'm off-my-rocker on what I think is the problem.

**Comment by grimlockrocks** [comment]
@troyibm In my Alexa sample app, I am actually using KITT Swift 3 example: https://github.com/Kitt-AI/snowboy/tree/master/examples/iOS/Swift3/SnowboyTest. If you look at the implementation: https://github.com/Kitt-AI/snowboy/blob/master/examples/iOS/Swift3/SnowboyTest/SnowboyWrapper.mm#L38, it basically takes the audio array and compare it with the trained wake word audio array. 

I never tested two-word phrase, but here are my thoughts that may help improve the accuracy:
* When you set a timer to run wake word detection, set a longer period, e.g. 2 seconds, 3 seconds, which will increase the chance that your audio file contains all the keywords.
* A better solution I think is to add another buffer array in the above .mm file, keep a rolling window of two buffer arrays, merge them together, and then call snowboy->RunDetection. This will help when "hey" is in the first audio file passed in, while "jackson" is in the second audio file passed in. 

I cannot see the implementation of snowboy->RunDetection, the KITT team may help you understand how the data is analyzed. 

Hope this helps!

**Comment by chenguoguo** [comment]
```
 I think it is because the detection is done on a buffer size and if the wake phrase audio splits between buffers, then it won't be detected. 
```

That is not the case. Snowboy has an internal buffer which takes care of the hotword context. For end users, as long as you can feed the audio to Snowboy chunk by chunk, that should be enough. Internally we don't distinguish a single hotword or hotword phrases.

It's possible that the Swift 3 example doesn't cover some corner cases. Could you also give the Python demo a shot, just to make sure if the issue relates to the model or the example?

**Comment by troyibm** [comment]
Thanks for the reply Sheng.  A colleague of mine suggested a ring buffer, which is what the python example does.  Not sure how to implement that in Swift, but I haven't tried to find an example yet.
https://en.wikipedia.org/wiki/Circular_buffer
While a longer period would help find the entire phrase better, it will also give a pause to the user.

**Comment by troyibm** [comment]
@chenguoguo I'm trying to try the python example but I'm stuck on trying to install pyaudio.  I get this error (I have Xcode installed, I have portaudio 19.6.0.  I have python 2.7.10 running on macOS 10.12.4.

~/git/snowboy/examples/Python$ pip install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/c4/fsn7gpkx1f988_ysm2j05htr0000gn/T/pip-build-FK6t2z/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c4/fsn7gpkx1f988_ysm2j05htr0000gn/T/pip-HZJNKy-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    copying src/pyaudio.py -> build/lib.macosx-10.12-intel-2.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.macosx-10.12-intel-2.7
    creating build/temp.macosx-10.12-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DMACOSX=1 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_portaudiomodule.c -o build/temp.macosx-10.12-intel-2.7/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/c4/fsn7gpkx1f988_ysm2j05htr0000gn/T/pip-build-FK6t2z/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c4/fsn7gpkx1f988_ysm2j05htr0000gn/T/pip-HZJNKy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/c4/fsn7gpkx1f988_ysm2j05htr0000gn/T/pip-build-FK6t2z/pyaudio/

**Comment by troyibm** [comment]
also tried suggestion on this SO http://stackoverflow.com/questions/33513522/when-installing-pyaudio-pip-cannot-find-portaudio-h-in-usr-local-include

still not installing pyaudio

**Comment by troyibm** [comment]
got it.. had to use sudo on that SO suggestion.. eek.

**Comment by troyibm** [comment]
Following these instructions: https://github.com/Kitt-AI/snowboy#quick-start-for-python-demo

still having problems:
>>> import snowboydecoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snowboydecoder.py", line 5, in <module>
    import snowboydetect
ImportError: No module named snowboydetect

**Comment by chenguoguo** [comment]
Did you compile it under swig/Python? Also make sure you use swig 3.0.10 or above.

**Comment by troyibm** [comment]
no.. just figured that out.. have 3.0.12 of swig

**Comment by troyibm** [comment]
works every time for the python version.  Doesn't look like it is the pmdl file.

**Comment by chenguoguo** [comment]
So the problem is from the Swift3 example. I don't have much experience with Swift3, perhaps someone else with more experience can jump in?

**Comment by troyibm** [comment]
The Swift3 example it does the following:
- sets a timer that fires every set number of seconds (I have set to 2) 
- when timer fires, it records to a file for some set number of seconds (I was using 1 second but Sheng suggested longer, so I am using 2 now).  After the recording is finished, it runs the contents of the file through snowboy->RunDetection.  If result is 1, it stops the process.  If result isn't one, it does nothing because the timer will fire again and start the process over.

That doesn't seem right at all.

I think it should always be recording and always be reading from the same buffer. (the circular buffer I mentioned earlier).

**Comment by chenguoguo** [comment]
Hmm, yes that's not optimal. If you are familiar with Swift3, it will be great if you can improve it by adopting some of the logics from the Python demo.

**Comment by troyibm** [comment]
I think if I was to go through this exercise, I would start with https://github.com/raywenderlich/swift-algorithm-club/tree/master/Ring%20Buffer

This is stuff I'm not an expert at so it will take me some time or I might not succeed at all.  @grimlockrocks you want to take a crack at it?  Seems the Swift example would be much more improved if it used the same technique as the python example.

**Comment by troyibm** [comment]
@chenguoguo is the Java/Android example for snowboy use the same logic as the Python demo?

**Comment by chenguoguo** [comment]
Yes.
