### ISSUE TITLE
Cannot Import SnowBoyDecoder

### ISSUE THREAD

**Issue by TheMadCoder1** [Kitt-AI/snowboy#196]
When I try to import SnowBoyDecoder, I get the following error stack trace:

	Traceback (most recent call last):
	  File "test.py", line 1, in <module>
		import snowboydecoder
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydecoder.py", line 5, in <module>
		import snowboydetect
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydetect.py", line 28, in <module>
		_snowboydetect = swig_import_helper()
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydetect.py", line 24, in swig_import_helper
		_mod = imp.load_module('_snowboydetect', fp, pathname, description)
	  File "/usr/lib/python3.5/imp.py", line 242, in load_module
		return load_dynamic(name, filename, file)
	  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
		return _load(spec)
	ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

What is this error and how do I fix it? Please help me ASAP, this is part of my Hackathon project due in 15 hours.

**Comment by chenguoguo** [comment]
You should install ATLAS by running ` sudo apt-get install libatlas-base-dev`, let me know if it works. Good luck on your hackathon!

**Comment by TheMadCoder1** [comment]
It did solve some problems. Running in Python2 is now working. However, Python3 still throws an error, but a different error this time:
Traceback (most recent call last):
	  File "main.py", line 2, in <module>
		import snowboydecoder
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydecoder.py", line 5, in <module>
		import snowboydetect
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydetect.py", line 28, in <module>
		_snowboydetect = swig_import_helper()
	  File "/home/rohan/Code_Projects/Hackathons/CodeDay/powerpointspeech/snowboydetect.py", line 24, in swig_import_helper
		_mod = imp.load_module('_snowboydetect', fp, pathname, description)
	  File "/usr/lib/python3.5/imp.py", line 242, in load_module
		return load_dynamic(name, filename, file)
	  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
		return _load(spec)
	ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

How can I fix this error? And also, out of curiosity, what was the last error about, and why did installing ATLAS fix things?

Your fix is enough for the Hackathon and for giving my team a working application. Thank you so much! The Snowboy API was a dream come true for us.
