### ISSUE TITLE
UnsatisfiedLinkError when trying the Java Wrapper

### ISSUE THREAD

**Issue by LookitheFirst** [Kitt-AI/snowboy#226]
Hi, so I'm trying to use the Java Wrapper for Snowboy, but not even the sample will work for me. After fiddling around a bit I managed to compile a program, but when running I get the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: snowboyJNI.new_SnowboyDetect(Ljava/lang/String;Ljava/lang/String;)J
	at snowboyJNI.new_SnowboyDetect(Native Method)
	at SnowboyDetect.<init>(SnowboyDetect.java:37)
	at Test.main(Test.java:21)

```
What could be the reason for this?

My Test.java file looks like this:

```
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.TargetDataLine;

public class Test {
    static {
        System.loadLibrary("snowboy-detect-java");
    }

    public static void main(String[] args) {
        // Sets up audio.
        AudioFormat format = new AudioFormat(16000, 16, 1, true, false);
        DataLine.Info targetInfo = new DataLine.Info(TargetDataLine.class, format);

        // Sets up Snowboy.
        SnowboyDetect detector = new SnowboyDetect("resources/common.res",
                "resources/snowboy.umdl");
        detector.SetSensitivity("0.5");
        detector.SetAudioGain(1);

        try {
            /*irrelevant for now*/
        } catch (Exception e) {
            System.err.println(e);
        }
    }
}
```

My files are all in the same Folder:

```
SnowboyJava/
├── resources/
│   ├── common.res
│   └── snowboy.umdl
├── libsnowboy-detect-java.so
├── SnowboyDetect.java
├── snowboyJNI.java
├── Test.java
└── snowboy.umdl
```

OS: Ubuntu 16.04 LTS

**Comment by chenguoguo** [comment]
Did you do `make` under `swig/Java`? What was your swig version?

Could you post the errors when you first `make` under `swig/Java`, then run `javac -classpath java Demo.java` under `examples/Java`, and finally run `java -classpath .:java -Djava.library.path=jniLibs Demo` under `examples/Java`?

**Comment by LookitheFirst** [comment]
Ok, first the SWIG-Version:
```
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre
```

When executing `make` under `swig/Java`:

```
swig -I../../ -c++ -java -package ai.kitt.snowboy -outdir \
  java/ai/kitt/snowboy/ -o snowboy-detect-swig.cc snowboy-detect-swig.i
g++ -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -shared  snowboy-detect-swig.o \
  ../..//lib/ubuntu64/libsnowboy-detect.a -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o jniLibs/libsnowboy-detect-java.so
```

When executing `javac -classpath java Demo.java` the command gets executed without any output
When executing `java -classpath .:java -Djava.library.path=jniLibs Demo` the command starts running without any output and only stops after `CTRL-C`ing
