### ISSUE TITLE
setup.py builds for python2.7 by default

### ISSUE THREAD

**Issue by rrueth** [Kitt-AI/snowboy#229]
I was trying to build a wheel for snowboy today.  I was able to run `make -C swig/Python3` without an issue.  Then, I tried to build a python3 wheel with `python3 setup.py bdist_wheel`.  The wheel was generated successfully.  After I pip installed the wheel, when I would `import snowboy.snowboydetect`, I would get the following error:

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/witch-embedded_ryan-jenkins-46SLYHB2NXEVQC6RFB2HH47UX37ZRZKDTTQ6MRH32S7SYKU72VBQ/env/lib/python3.5/site-packages/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/var/lib/jenkins/workspace/witch-embedded_ryan-jenkins-46SLYHB2NXEVQC6RFB2HH47UX37ZRZKDTTQ6MRH32S7SYKU72VBQ/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/jenkins/workspace/witch-embedded_ryan-jenkins-46SLYHB2NXEVQC6RFB2HH47UX37ZRZKDTTQ6MRH32S7SYKU72VBQ/env/lib/python3.5/site-packages/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/var/lib/jenkins/workspace/witch-embedded_ryan-jenkins-46SLYHB2NXEVQC6RFB2HH47UX37ZRZKDTTQ6MRH32S7SYKU72VBQ/env/lib/python3.5/site-packages/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/var/lib/jenkins/workspace/witch-embedded_ryan-jenkins-46SLYHB2NXEVQC6RFB2HH47UX37ZRZKDTTQ6MRH32S7SYKU72VBQ/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_snowboydetect'
```

I realized that the setup.py file referenced `swig/Python` and `examples/Python` in four places.  I changed all of these to `Python3` instead.  After rebuilding the wheel, reinstalling, and importing, everything worked.

Is there something that can be done to update the setup.py file to build for python2 vs python3 without requiring the user to change the file?

**Comment by chenguoguo** [comment]
I'm not too sure what is the best way to handle this. Perhaps @leosampaio can give some suggestions?

**Comment by rrueth** [comment]
Could you use something like the following?
```python
import sys

if sys.version_info.major == 3:
  # Use "Python3"
else:
  # Use "Python"
```

**Comment by leosampaio** [comment]
Hi all; great suggestion @rrueth, I will try and have a look at this by next week and will let you know if it works out 😄

**Comment by rrueth** [comment]
Thanks, @leosampaio!  Let me know if there is anything that I can do to help.
