### ISSUE TITLE
Cannot find module - electron-v1.6-linux-arm

### ISSUE THREAD

**Issue by dolanmiu** [Kitt-AI/snowboy#246]
One of the users for my library is getting this error:

```
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-linux-arm/snowboy.node'
```

Any particular reason for this?

Full log here:
```
0|mm | at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
0|mm | at Module._compile (module.js:571:32)
0|mm | at Object.Module._extensions..js (module.js:580:10)
0|mm | at Module.load (module.js:488:32)
0|mm | { Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-linux-arm/snowboy.node'
0|mm | at Module._resolveFilename (module.js:470:15)
0|mm | at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm | at Function.Module._load (module.js:418:25)
0|mm | at Module.require (module.js:498:17)
0|mm | at require (internal/module.js:20:19)
0|mm | at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
0|mm | at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
0|mm | at Module._compile (module.js:571:32)
0|mm | at Object.Module._extensions..js (module.js:580:10)
0|mm | at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
```

@mc-landin

**Comment by dolanmiu** [comment]
You can close this, he has resolved the issue

And oh yeah, I posted #187 haha

**Comment by Bala0804** [comment]
@dolanmiu, @chenguoguo  How this issue was resolved?
