### ISSUE TITLE
Cannot install through npm - Ubuntu 16.04

### ISSUE THREAD

**Issue by ivosequeros** [Kitt-AI/snowboy#258]
When trying to install using 'npm install snowboy', I get the following output:
(It seems that the URL http://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-x64.tar.gz is not accessible and returns a 403 Error)

```

> snowboy@1.2.0 preinstall /home/host/grayscale/node_modules/snowboy
> npm install node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.36
added 112 packages in 15.561s

> snowboy@1.2.0 install /home/host/grayscale/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/host/grayscale/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:135: recipe for target 'Release/obj.target/snowboy.node' failed
make: *** [Release/obj.target/snowboy.node] Error 1
make: Leaving directory '/home/host/grayscale/node_modules/snowboy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-28-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64"
gyp ERR! cwd /home/host/grayscale/node_modules/snowboy
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/host/grayscale/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.10.0-28-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/host/grayscale/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/host/grayscale/node_modules/snowboy
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/host/grayscale/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by ivosequeros** [comment]
Well, I just saw that you don't support Ubuntu 16.XX.
