### ISSUE TITLE
Snowboy on RASPIAN!! Not windows!!

### ISSUE THREAD

**Issue by ericlfr** [Kitt-AI/snowboy#267]
Hi,

I try to launch a demo.py from "snowboy-master\examples\Python"

Here is the result:

python demo.py snowboy.umdl -d
Traceback (most recent call last):
File "demo.py", line 1, in
import snowboydecoder
File "/home/pi/snowboy-master/examples/Python/snowboydecoder.py", line 5, in
import snowboydetect
File "/home/pi/snowboy-master/examples/Python/snowboydetect.py", line 1
../../swig/Python/snowboydetect.py
^
SyntaxError: invalid syntax

I changed the snowboydetect.py from

../../swig/Python/snowboydetect.py

to

import sys
sys.path.append("../../swig/Python")
import snowboydetect

and here is the result:

python demo.py snowboy.umdl -d
Traceback (most recent call last):
File "demo.py", line 27, in
detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
File "/home/pi/snowboy-master/examples/Python/snowboydecoder.py", line 90, in init
self.detector = snowboydetect.SnowboyDetect(
AttributeError: 'module' object has no attribute 'SnowboyDetect'

I've been able to verify that SnowboyDetect is in file "/home/pi/snowboy-master/swig/Python/snowboydetect.py"

I do not understand what happens...

!!!!!!! Working on raspian no windows!!!!!!!!

Could you help me please?

**Comment by cwxyz007** [comment]
I have the some problem.

It seems `snowboydetect.py` not link correct. So I try to force link it, and it works for me.

![image](https://user-images.githubusercontent.com/14226737/64578446-013e2480-d3b2-11e9-9d6d-6cf61016b16f.png)

```sh
# step 1, go to swig/Python folder
cd snowboy/swig/Python
# step 2, force link `snowboydetect.py` to the correct path
# `/home/pi/snowboy-master/examples/Python/snowboydetect.py` is the path in the above picture
ln snowboydetect.py /home/pi/snowboy-master/examples/Python/snowboydetect.py -f
```

Hope helpful.

**Comment by evancohen** [comment]
> Note: Snowboy does not support Windows yet. Please build Snowboy on *nix platforms.
