### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by c4tz** [Kitt-AI/snowboy#279]
I got it working now, but there are some things you should consider.

As [this post](https://bbs.archlinux.org/viewtopic.php?pid=1682302#p1682302) says, 

> lapack_atlas.so is created by a debian-specific patch to the upstream makefile, so that makefile will not work on any non debian system

So after installing `atlas-lapack` from the AUR (which made me change my CPU Frequency through GRUB in order to install it), `make` still threw this error:

```
/usr/bin/ld: cannot find -llapack_atlas
```

to overcome this, one needs to change 

```
LDLIBS := -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas
```
to
```
LDLIBS := -lm -ldl -lf77blas -lcblas -llapack -latlas
```
as described in the post mentioned above.

What I want to say is: Maybe there should be a check if either `lapack_atlas` or `lapack` is installed and be chosen inside the Makefile.

That would save people a lot of time and also make the pip package installable on Arch Linux :)

**Comment by chenguoguo** [comment]
Normally on Linux `lapack_atlas` will be part of the `atlas` installation. How did you install `atlas`?

**Comment by c4tz** [comment]
I installed `atlas-lapack` from the AUR ([link](https://aur.archlinux.org/packages/atlas-lapack/)).

**Comment by chenguoguo** [comment]
OK looks like Arch Linux is a little bit different. It will be great if you can come up with a pull request.

**Comment by c4tz** [comment]
Done https://github.com/Kitt-AI/snowboy/pull/280

Maybe providing an AUR package for python-snowboy would make sense, because the dependencies could be resolved easily. If I have enough time, I'll look into that.

By the way: Thank you for the fantastic work! :)

**Comment by NicoHood** [comment]
Can anybody please tell me how to get a simple snowboy demo to run on Arch Linux? I am using the AUR package of snowboy:
https://aur.archlinux.org/packages/python-snowboy-git/

Then I downloaded this git, navigated to the Python3 example folder and removed "from ." in line 5 of nano snowboydecoder.py so it uses the system wide python library. But when I run the actual python demo i get the following error:

```
python demo.py ../../resources/models/snowboy.umdl 
Listening... Press Ctrl+C to exit
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```

Can anyone help me please?

**Comment by chenguoguo** [comment]
Could you verify that you have set up the audio properly? See here: http://docs.kitt.ai/snowboy/#set-up-audio

**Comment by NicoHood** [comment]
```
$ rec t.wav

Input File     : 'default' (pulseaudio)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:07.77 [00:00:00.00] Out:369k  [      |      ]        Clip:0    ^C
Aborted.
```

Seems to work. I can also hear myself in the recorded sound file. I am not using a Raspberry pi (as its written everywhere in the docs), I am using a normal i7 CPU.

**Comment by chenguoguo** [comment]
What about `rec -r 16000 -t wav test.wav`?

**Comment by NicoHood** [comment]
This also works.

**Comment by chenguoguo** [comment]
What if you check out from our repository directly, compile the so library through swig for Python, and run the demos? I think that should work for you?

I haven't tried the aru package myself. If Snowboy alone works, perhaps @c4tz can help us look at the package.

**Comment by NicoHood** [comment]
I tried again with the following commands (full output [here](https://gist.github.com/NicoHood/1b7f8c8e97c158e8f80eb2cae004f6a5)):

```
28352  git clone git@github.com:NicoHood/snowboy.git
28353  cd snowboy
28354  git remote add upstream git@github.com:Kitt-AI/snowboy.git
28355  git fetch --all
28356  git checkout v1.3.0 
28357  cd swig/Python3/
28358  ls
28359  make
28360  sed -i "s|-lf77blas -lcblas -llapack -latlas|-lcblas -llapack|g" Makefile 
28361  make
28362  ls
28363  cd ../../examples/Python3/
28364  ls
28365  ls -la
28366  python3 demo.py
```

The most recent error is:
```
$ python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/arch/hackallthethings/snowboy/examples/Python3/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
ImportError: attempted relative import with no known parent package
```

It seems there is something wrong with the symlinks. Another thing to note is that I removed the atlas libraries (as in the arch package). If they are not required, why are they added there as link option? Can't you remove them?

Could you give me a quick hint how to setup the symlinks correct, so the import works? I guess this is a general issue, does it work for you?

**Comment by NicoHood** [comment]
I also have the same problem with the c++ example by the way:

```
make[1]: Leaving directory '/home/arch/hackallthethings/snowboy/examples/C++/portaudio'
g++ -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -msse  -msse2 -I../../ -std=c++0x -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -rdynamic -DHAVE_POSIX_MEMALIGN -Iportaudio/install/include -O3    demo.cc portaudio/install/lib/libportaudio.a ../..//lib/ubuntu64/libsnowboy-detect.a   -ldl -lm -Wl,-Bstatic -Wl,-Bdynamic -lrt -lpthread portaudio/install/lib/libportaudio.a -L/usr/lib/atlas-base -lf77blas -lcblas -llapack_atlas -latlas -lasound -o demo
/usr/bin/ld: cannot find -lf77blas
/usr/bin/ld: cannot find -llapack_atlas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [<builtin>: demo] Error 1
[arch@talloniv C++]$ g++ -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -msse  -msse2 -I../../ -std=c++0x -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -rdynamic -DHAVE_POSIX_MEMALIGN -Iportaudio/install/include -O3    demo.cc portaudio/install/lib/libportaudio.a ../..//lib/ubuntu64/libsnowboy-detect.a   -ldl -lm -Wl,-Bstatic -Wl,-Bdynamic -lrt -lpthread portaudio/install/lib/libportaudio.a -L/usr/lib/atlas-base -lcblas -llapack -lasound -o demo
[arch@talloniv C++]$ ./demo 
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
Listening... Press Ctrl+C to exit
^CCaught signal 2, terminating...
```

Same question  here is why atlas is used as link open, even if its not essentially required? Is this an old dependency which you forget to remove?

Also I am wondering why you are downloading portaudio instead of using a distribution package? Is this only because debian ships too old packages? For Arch Linux this may not apply so the distribution package could be used?

**Comment by NicoHood** [comment]
I just noticed that the example is actually working. The errors can be "ignored", the hotword detection is function. However those errors should not appear if you ask me.

**Comment by chenguoguo** [comment]
Those errors were spit out by PortAudio and we don't really have control on that.

**Comment by NicoHood** [comment]
That is possible.

What about the wrong(?) import command or broken(?) symlink of the Python example?

What about the atlas linkage. Is it still required and why does it work without?

**Comment by chenguoguo** [comment]
There are various implementations for cblas, and atlas is one of them. Most of the time people install atlas so they get cblas, see the dependencies in the documentation:

https://github.com/Kitt-AI/snowboy#ubunturaspberry-pipine64nvidia-jetson-tx1nvidia-jetson-tx2

**Comment by NicoHood** [comment]
Yes, I also have cblas. However the makefile uses even more libraries which seem to be not essentially required. What about those? Why not remove them?

```diff
diff --git a/swig/Python3/Makefile b/swig/Python3/Makefile
index 5bf8b15..c4b9d4f 100644
--- a/swig/Python3/Makefile
+++ b/swig/Python3/Makefile
@@ -46,7 +46,7 @@ else
   ifneq ("$(ldconfig -p | grep lapack_atlas)","")
     LDLIBS := -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas
   else
-    LDLIBS := -lm -ldl -lf77blas -lcblas -llapack -latlas
+    LDLIBS := -lm -ldl -lcblas -llapack
   endif
   SNOWBOYDETECTLIBFILE = $(TOPDIR)/lib/ubuntu64/libsnowboy-detect.a
   ifneq (,$(findstring arm,$(shell uname -m)))
```
