### ISSUE TITLE
Ubuntu 16.04 python demo.py snowboy.pmdl

### ISSUE THREAD

**Issue by gpavankv** [Kitt-AI/snowboy#285]
~/Downloads/SB$ python demo.py snowboy.pmdl
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/gpavankv/Downloads/SB/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/gpavankv/Downloads/SB/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/gpavankv/Downloads/SB/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

this is the erro i get when i run python demo.py snowboy.pmdl on Ubuntu. 

What do i do?

**Comment by gpavankv** [comment]
there was a solution where i had to install some other libraries. Even after that i get this error! Kindly someone guide me on how to run snowboy on ubuntu

python demo.py snowboy.umdl
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/gpavankv/Downloads/s/examples/Python/snowboydecoder.py", line 5, in <module>
    import snowboydetect
ImportError: No module named snowboydetect

**Comment by gpavankv** [comment]
alexa.umdl and snowboy.umdl where in resources directory. They should actually be in the same level as the demo.py

**Comment by chenguoguo** [comment]
You can always use something like `python demo.py resources/snowboy.pmdl`
