### ISSUE TITLE
npm install failed - pre-built binaries forbidden to download

### ISSUE THREAD

**Issue by Y0nnyy** [Kitt-AI/snowboy#306]
Hallo there,

i wanted to download and install snowboy. But in tells me that downloading the pre-built-binaries is forbidden (403). Also tried without npm to download them (also 403). 
````
Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-arm.tar.gz  
````

And the node-gyp compiler throw an error:
````
module.js:529
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:624:30)
    at evalScript (bootstrap_node.js:462:27)
````

So what am i doing wrong?

**Comment by Y0nnyy** [comment]
Obviously it has something to do with my technology, not the project -> closed
