### ISSUE TITLE
[Python3]SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by chandong83** [Kitt-AI/snowboy#316]
I get the following error:

Traceback (most recent call last):
File "demo.py", line 1, in <module>
import snowboydecoder
File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 5, in <module>
from . import snowboydetect
SystemError: Parent module '' not loaded, cannot perform relative import

I changed it as follows.
in snowboy/examples/Python3/snowboydecoder.py
<5line>
<pre>
<code>
from . import snowboydetect
to 
import snowboydetect
</code>
</pre>

it is work.
but This way is not good for that project.

so How about the following?
<pre>
<code>

from os.path import dirname
# get the current path.
curpath = dirname(__file__)

import imp
snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')
</code>
</pre>

**Comment by chenguoguo** [comment]
Where are you running the script? Is it under `examples/Python3/`?

**Comment by chandong83** [comment]
yes. 
i tried command below
<pre>
pi@raspberrypi:~/snowboy/examples/Python3 $ python3 demo.py resources/snowboy.umdl
</pre>

**Comment by chenguoguo** [comment]
I understand this should work
```
from os.path import dirname
# get the current path.
curpath = dirname(__file__)

import imp
snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')
```

but is this the standard way in a Python package? Probably not?

**Comment by hack-r** [comment]
I also had this problem. The code block mentioned above didn't work for me for some reason (tried a few variations). What did work was to comment out `from . import snowboydetector` and edit `curpath` out of `snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')`. This allowed me to return to Jack server error issues :)

**Comment by maroonsp1rit** [comment]
I'd just like to point out that this issue still persists. When trying to launch the demo the same error still occurs, requires editing to get it to launch properly which doesn't seem to be the best case

`(snowboyenv) pi@raspberrypi:~/Snowboy/snowboy/examples/Python3 $ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snowboydecoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Snowboy/snowboy/examples/Python3/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by fl118543** [comment]
The module imp is deprecated since Pÿthon 3.4 so if you want to use a later version of python you should use the importlib module. You'll have to modify snowboydecoder and replace "from . import snowboydetect" by:

import importlib
importlib.import_module("snowboydetect")

### Example:
**Before the modification:**

$ python3 demo4.py 
Traceback (most recent call last):
  File "demo4.py", line 1, in <module>
    import snowboydecoder
  File "/home/francois/DEV/Android_apk/snowboy/examples/Python3/snowboydecoder.py", line 7, in <module>
    from . import snowboydetect
ImportError: attempted relative import with no known parent package

**After the modification:**

$ python3 demo4.py 
Error: need to specify model name
Usage: python demo.py your.model

Hope this help,
Francois

**Comment by Prskriti** [comment]
@fl118543 thank you ur query reply helped me a lot

**Comment by Prskriti** [comment]
But now I am facing another type of issue .Please anyone help me in resolving this issue:

>>> import snowboydetect
>>> import snowboydecoder
>>> def detected_callback():
...     print("Wake Word Detected")
... 
>>> detector=snowboydecoder.HotwordDetector("resources/models/snowboy.umdl",sensitivity=0.5,audio_gain=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prakriti/snowboy/examples/Python3/snowboydecoder.py", line 112, in __init__
    self.detector = snowboydetect.SnowboyDetect(
NameError: name 'snowboydetect' is not defined
>>>

**Comment by PROQAQ** [comment]
The same error kept bothering me.Thank you for your previous efforts and the written record provided.I will always be grateful to you!A little boy from China

**Comment by KilliannH** [comment]
I mean... you should really merge this code from @chandong83 : 
from os.path import dirname
# get the current path.
curpath = dirname(__file__)

import imp
snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')

**Comment by liziru** [comment]
@fl118543  I tried your advice but other problems same as @Prskriti occured . Anyone can help me? Thanks.

**Comment by SwithFr** [comment]
Hi! Same error as @Prskriti and @liziru... any advice ?

**Comment by KilliannH** [comment]
Yes, if you have the @Prskriti error, it means you haven't compiled snowboy in your python3 env dependencies.

here are some steps to make snowboy running :

sudo apt-get install portaudio19-dev
sudo apt-get install libatlas-base-dev
sudo apt-get install libpcre3-dev

download swig at http://www.swig.org/.
extract swig-v3.x.x
cd swig-v3.x.x

./configure

sudo make
sudo make install

download snowboy-master from github as zip file
cd swig/Python3

swig snowboy-detect-swig.i

copy the generated files : snowboydecoder.py & snowboydetect.py to your project

Done ! :) 👍
