### ISSUE TITLE
Cannot run over ssh, works fine locally

### ISSUE THREAD

**Issue by darwinasm86** [Kitt-AI/snowboy#328]
I have run this script many times, but for some reason I cannot get this to work over SSH.

I discovered this when trying to get this to run on boot.

JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/Woof/rpi-arm-raspbian-8.0-1.1.1/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

**Comment by chenguoguo** [comment]
It was not able to find your microphone (or your microphone didn't support 16k sampling rate) through your setup.

**Comment by darwinasm86** [comment]
How is that possible, I can walk two feet over to the pi and use the mouse and keyboard there to run from the same directory same exact command and it works every time.

**Comment by chenguoguo** [comment]
Probably it was loading certain audio related libraries before the library was ready

**Comment by darwinasm86** [comment]
How do I fix it, I’d like to run the script on boot but this error keeps happening and I have to manually start it from the console.

**Comment by chenguoguo** [comment]
It never happened to me, so I don't know how to fix it.

It's not really a Snowboy issue. The problem was related to audio capturing using PortAudio. If it doesn't work, you can try to use other options, e.g., https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/demo_arecord.py

**Comment by darwinasm86** [comment]
I will talk to some people and see if they have a feel for this issue and what it might take to solve it.
