### ISSUE TITLE
Issue installing on mac, node v8.9.1

### ISSUE THREAD

**Issue by alexdufetel** [Kitt-AI/snowboy#339]
I have previously been able to install - and use - snowboy on mac, but for some reason I am no longer able to install the package in a new project. 

node  version: v8.9.1
npm version: 5.6.0

ran:
brew install swig portaudio sox
pip install pyaudio

installed nan,  node-record-lpcm16, request, snowball, thunkify-wrap, co, q, fs

I get the following error:

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.9.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
**clang: error: no such file or directory: 'D/Devs/testsnow/snowboy/include'
make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1**
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64/snowboy.node" "--module_name=snowboy" "--module_path=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64"
gyp ERR! cwd /Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64/snowboy.node --module_name=snowboy --module_path=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/adufetel/Documents/Alex D/Devs/testsnow/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy
node-pre-gyp ERR! node -v v8.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64/snowboy.node --module_name=snowboy --module_path=/Users/adufetel/Documents/Alex D/Devs/testsnow/snowboy/lib/node/binding/Release/node-v57-darwin-x64' (1)
npm WARN testsnow@1.0.0 No description
npm WARN testsnow@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adufetel/.npm/_logs/2018-01-01T01_50_30_834Z-debug.log

**Comment by chenguoguo** [comment]
Were you previously using node v8.9.1? I believe we still have problems with node v8.

**Comment by alexdufetel** [comment]
yes, though it may not have been that exact version. Which version of node do you recommend?

**Comment by chenguoguo** [comment]
I just checked and we have not yet successfully built snowboy-v1.2.0-node-v57-darwin-x64.tar.gz. Most likely you were using node v7, or you were compiling Snowboy for node v8 from source?

**Comment by alexdufetel** [comment]
Yes, if I remember correctly I was compiling from source. I'll revert to node v7 for now. thanks

**Comment by dmytrobr** [comment]
which node version I should use to install snowboy? I'm getting this error on MacOS 10.14.3

 "Pre-built binaries not found for snowboy@1.2.0 and node@10.14.2"

Same for 1.3.1 (latest) version of snowboy
