### ISSUE TITLE
Python 3 / Pi -- SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by hack-r** [Kitt-AI/snowboy#387]
I cloned the `snowboy` repo, installed the dependencies, checked that I could record audio with `rec`, and successfully ran `make` under `swig/Python3`.

The demo gives me this error:

> 
> python examples/Python3/demo.py 
> Traceback (most recent call last):
>   File "examples/Python3/demo.py", line 1, in <module>
>     import snowboydecoder
>   File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 5, in <module>
>     from . import snowboydetect
> SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by hack-r** [comment]
I realized this is a duplicate
