### ISSUE TITLE
New Jarvis.umdl freezes

### ISSUE THREAD

**Issue by meischdaddy30** [Kitt-AI/snowboy#469]
I'm using this hotword with MMM-Assistant and heres how it is in my module

file: 'resources/models/jarvis.umdl',
sensitivity: '0.8,0.80',
hotwords: ['jarvis','jarvis']

And when I start my mirror and say "jarvis" it gives the ding when it recognizes the hotword but then the microphone turns red and freezes like that.  My whole MM is still working and shuffling through my other modules just my assistant is frozen.  My assistant works great with snowboy but I would really like jarvis.

Can anybody shed some light on this for me please?  This is the last thing I'd like to do before it's finished.  Thanks guys.

**Comment by meischdaddy30** [comment]
Here's my error

0|MagicMir |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|MagicMir |     at emitTwo (events.js:126:13)
0|MagicMir |     at Socket.emit (events.js:214:7)
0|MagicMir |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|MagicMir |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by meischdaddy30** [comment]
Now it's just saying ` [ASSTNT] Snowboy Activated ` and nothing

**Comment by meischdaddy30** [comment]
Question about changing ApplyFrontend to true
