### ISSUE TITLE
python3 demo.py mode.pmdl - ImportError: No module named 'snowboydetect'

### ISSUE THREAD

**Issue by damianchoc** [Kitt-AI/snowboy#486]
i done everything in instruction and still get 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/Desktop/snowboy/snowboy/examples/Python3/snowboydecoder.py", line 6, in <module>
    import snowboydetect
ImportError: No module named 'snowboydetect'

what can i do with this?

**Comment by liziru** [comment]
I come to the same problem and still do not find helpful solution. I want to cry...
