### ISSUE TITLE
prompting snowboy to record

### ISSUE THREAD

**Issue by gbernal** [Kitt-AI/snowboy#488]
I have a function that records sound using pyaudio but I get the following error when running it from snowboy 
`connect(2)call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
  File "demo_arecord.py", line 79, in <module>
    sleep_time=0.03)
  File "/home/pi/Documents/AH_project/Project_Andy/snowboydecoder_arecord.py", line 170, in start
    callback()
  File "demo_arecord.py", line 35, in recordAudio
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid input device (no default output device)] -9996`

it looks to me that the device is being used by snowboy and generates the no output device error.

How can I get around this issue?

code below..
```
import snowboydecoder_arecord as snow_a
import sys
import signal
import wave
import pyaudio
interrupted = False
numRec = 0

def multipleFeedback():
    snow_a.play_audio_file
    print('*****************  ok! ***********')
    
def signal_handler(signal, frame):
    global interrupted
    interrupted = True


def interrupt_callback():
    global interrupted
    return interrupted

def recordAudio(i=[0]):
    i[0]+=1
    FORMAT = pyaudio.paInt16
    CHANNELS = 1
    RATE = 48000
    CHUNK = 1024 
    RECORD_SECONDS = 3 
   
    audio = pyaudio.PyAudio()
    global numRec 
    # start Recording
    stream = audio.open(format=FORMAT, channels=CHANNELS,
                    rate=RATE, input=True,
                    frames_per_buffer=CHUNK)
    print "recording..."
    frames = []
     
    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        frames.append(data)
    print "finished recording"
     
     
    # stop Recording
    stream.stop_stream()
    stream.close()
    audio.terminate()
    
    waveFile = wave.open('data%s.wav'% numRec, 'wb')
    waveFile.setnchannels(CHANNELS)
    waveFile.setsampwidth(audio.get_sample_size(FORMAT))
    waveFile.setframerate(RATE)
    waveFile.writeframes(b''.join(frames))
    waveFile.close()
    numRec +=1
    multipleFeedback()    
    
if len(sys.argv) == 1:
    print("Error: need to specify model name")
    print("Usage: python demo.py your.model")
    sys.exit(-1)

model = sys.argv[1]

# capture SIGINT signal, e.g., Ctrl+C
signal.signal(signal.SIGINT, signal_handler)

detector = snow_a.HotwordDetector(model, sensitivity=0.5)
print('Listening... Press Ctrl+C to exit')

# main loop
detector.start(detected_callback=recordAudio,
               interrupt_check=interrupt_callback,
               sleep_time=0.03)

detector.terminate()
```

**Comment by gbernal** [comment]
I just found out that demo4.py provides this feature, however it is meant to be used with pyaudio and not with arecord. Has anyone looked into this?
