### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6 in tid 31932 (.ai.snowboytest), pid 31932 (.ai.snowboytest)

### ISSUE THREAD

**Issue by garciaraul85** [Kitt-AI/snowboy#503]
I created a new Android project with Android studio, generated the .so files, added the assets and jniLibs inside a module project added the whole selfgenerated code inside the module project and in the app project added the DemoActivity, so when I run it I get a crash, though when I run the original demo project it works,
here is [my current test project](https://github.com/garciaraul85/snowboytest)

 here is the log:
```

09-06 12:00:29.175 261-10639/? E/installd: Failed to delete /data/app/vmdl2031054346.tmp: No such file or directory
09-06 12:00:29.739 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///alexa.umdl
09-06 12:00:29.743 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///common.res
09-06 12:00:29.746 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///ding.wav
09-06 12:00:29.749 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///hey angel.pmdl
09-06 12:00:29.753 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///hey_angel.pmdl
09-06 12:00:29.756 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///jarvis.umdl
09-06 12:00:29.758 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///smart_mirror.umdl
09-06 12:00:29.760 31932-31932/snowboy.kitt.ai.snowboytest E/AppResCopy: overriding file /storage/emulated/0/snowboy///snowboy.umdl
09-06 12:00:29.767 31932-31932/snowboy.kitt.ai.snowboytest E/AudioDataSaver: /storage/emulated/0/snowboy//recording.pcm
    
    --------- beginning of crash
09-06 12:00:29.771 31932-31932/snowboy.kitt.ai.snowboytest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31932 (.ai.snowboytest), pid 31932 (.ai.snowboytest)
09-06 12:00:29.811 31959-31959/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'google/ryu/dragon:8.1.0/OPM4.171019.021.Y1/4903051:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 31932, tid: 31932, name: .ai.snowboytest  >>> snowboy.kitt.ai.snowboytest <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
        x0   0000000000000000  x1   0000000000007cbc  x2   0000000000000006  x3   0000000000000008
        x4   feff1f01ff107bd4  x5   feff1f01ff107bd4  x6   feff1f01ff107bd4  x7   7f7f7f7f7f7f7fff
        x8   0000000000000083  x9   0000000010000000  x10  0000007ff06c1820  x11  0000000000000001
        x12  0000000000000001  x13  0000000000000000  x14  ffffffffffffffff  x15  ffffffffffffffff
        x16  0000007badfb8fa8  x17  0000007babb074b8  x18  0000000000000000  x19  0000000000007cbc
        x20  0000000000007cbc  x21  0000000000000083  x22  0000007b1e2b7540  x23  0000000000000004
        x24  0000000000000000  x25  0000007ff06c30f0  x26  0000000000000000  x27  0000000000000000
        x28  0000007ff06c3d50  x29  0000007ff06c1860  x30  0000007bababc6ec
        sp   0000007ff06c1820  pc   0000007bababc714  pstate 0000000060000000
09-06 12:00:29.836 31959-31959/? A/DEBUG: backtrace:
        #00 pc 000000000001d714  /system/lib64/libc.so (abort+120)
        #01 pc 00000000000ecae4  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (__gnu_cxx::__verbose_terminate_handler()+348)
        #02 pc 000000000009a740  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (__cxxabiv1::__terminate(void (*)())+8)
        #03 pc 00000000000ebd48  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so
        #04 pc 000000000009a1a8  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (__gxx_personality_v0+156)
        #05 pc 00000000000fe7a0  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so
        #06 pc 00000000000feac4  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (_Unwind_RaiseException+252)
        #07 pc 000000000009a8dc  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (__cxa_throw+124)
        #08 pc 000000000004cc14  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (snowboy::SnowboyLogMsg::~SnowboyLogMsg()+776)
09-06 12:00:29.837 31959-31959/? A/DEBUG:     #09 pc 00000000000497c4  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (snowboy::Input::Input(std::string const&)+500)
        #10 pc 000000000007cae4  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (snowboy::UnpackPipelineResource(std::string const&, std::string*)+72)
        #11 pc 00000000000414ac  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (snowboy::PipelineItf::SetResource(std::string const&)+452)
        #12 pc 000000000002b3ec  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (snowboy::SnowboyDetect::SnowboyDetect(std::string const&, std::string const&)+124)
        #13 pc 00000000000260c0  /data/app/snowboy.kitt.ai.snowboytest-Q1KXa78oRv40XjqvpbzxVA==/lib/arm64/libsnowboy-detect-android.so (Java_ai_kitt_snowboy_snowboyJNI_new_1SnowboyDetect+212)
        #14 pc 0000000000553bf0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
        #15 pc 000000000054ae4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
        #16 pc 00000000000dc5d0  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+264)
        #17 pc 000000000029b49c  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
        #18 pc 0000000000295a90  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+700)
        #19 pc 0000000000533f50  /system/lib64/libart.so (MterpInvokeStatic+264)
        #20 pc 000000000053ca94  /system/lib64/libart.so (ExecuteMterpImpl+14612)
        #21 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #22 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #23 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #24 pc 0000000000533d68  /system/lib64/libart.so (MterpInvokeDirect+356)
        #25 pc 000000000053ca14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
        #26 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #27 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #28 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #29 pc 0000000000533d68  /system/lib64/libart.so (MterpInvokeDirect+356)
        #30 pc 000000000053ca14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
        #31 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #32 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #33 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #34 pc 0000000000532ad8  /system/lib64/libart.so (MterpInvokeVirtual+652)
        #35 pc 000000000053c914  /system/lib64/libart.so (ExecuteMterpImpl+14228)
        #36 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #37 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #38 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #39 pc 0000000000532ad8  /system/lib64/libart.so (MterpInvokeVirtual+652)
        #40 pc 000000000053c914  /system/lib64/libart.so (ExecuteMterpImpl+14228)
        #41 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #42 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #43 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
09-06 12:00:29.838 31959-31959/? A/DEBUG:     #44 pc 0000000000532ad8  /system/lib64/libart.so (MterpInvokeVirtual+652)
        #45 pc 000000000053c914  /system/lib64/libart.so (ExecuteMterpImpl+14228)
        #46 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #47 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #48 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #49 pc 0000000000532ad8  /system/lib64/libart.so (MterpInvokeVirtual+652)
        #50 pc 000000000053c914  /system/lib64/libart.so (ExecuteMterpImpl+14228)
        #51 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #52 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #53 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #54 pc 0000000000533d68  /system/lib64/libart.so (MterpInvokeDirect+356)
        #55 pc 000000000053ca14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
        #56 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #57 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #58 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
        #59 pc 0000000000533d68  /system/lib64/libart.so (MterpInvokeDirect+356)
        #60 pc 000000000053ca14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
        #61 pc 0000000000275c00  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
        #62 pc 000000000027b7cc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
        #63 pc 0000000000295a70  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+668)
09-06 12:00:30.323 274-274/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_06
09-06 12:00:30.464 1284-1284/? E/PBSessionCacheImpl: sessionId[5648627893326241] not persisted.
09-06 12:00:59.201 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:00:59.263 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:00.001 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:00.095 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:00.115 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:00.141 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:00.162 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:01:05.949 373-390/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
09-06 12:01:05.950 561-561/? E/PhoneInterfaceManager: [PhoneIntfMgr] queryModemActivityInfo: Empty response
09-06 12:01:05.962 373-390/? E/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
09-06 12:01:30.637 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:03:00.037 373-386/? E/memtrack: Couldn't load memtrack module
09-06 12:03:08.877 837-30275/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:197301376>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/games
    gdv: Long live credential not available.
        at gdw.b(:com.google.android.gms@12874033@12.8.74 (090406-204998136):20)
        at gdw.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):50)
        at gcg.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):38)
        at hvg.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):8)
        at hvg.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):190)
        at hug.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):2)
        at hud.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):17)
        at hud.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):6)
        at dbd.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):25)
        at dbd.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):82)
        at fza.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):6)
        at fyz.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):2)
        at fyz.e(:com.google.android.gms@12874033@12.8.74 (090406-204998136):6)
        at fyy.a(:com.google.android.gms@12874033@12.8.74 (090406-204998136):1)
        at gax.getAuthToken(:com.google.android.gms@12874033@12.8.74 (090406-204998136):7)
        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:244)
        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
        at android.os.Binder.transact(Binder.java:627)
        at ddl.onTransact(:com.google.android.gms@12874033@12.8.74 (090406-204998136):3)
        at android.os.Binder.execTransact(Binder.java:697)
09-06 12:04:00.006 373-386/? E/memtrack: Couldn't load memtrack module

```

**Comment by garciaraul85** [comment]
It seems that I was missing adding the permissions at runtime, I suggest that the Android demo app be updated to reflect at least the MarshMellow runtime permissions
