### ISSUE TITLE
Error while using 'pip' to install snow boy. Windows 10

### ISSUE THREAD

**Issue by Edward-Zion-Saji** [Kitt-AI/snowboy#517]
#Error while using 'pip' to install snow boy. Windows 10
input to command prompt
```pip install snowboy```
Error
```
Collecting snowboy
  Using cached https://files.pythonhosted.org/packages/86/fc/3a13408cb3b32abff1b0539f44fca02ca378d9077b11f0c95674f278f3d
e/snowboy-1.2.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\EDWARD~1\AppData\Local\Temp\pip-install-fi9v8t6_\snowboy\setup.py", line 45, in <module>
        packages=find_packages('examples/Python/'),
      File "c:\users\edward zion saji\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py",
line 58, in find
        convert_path(where),
      File "c:\users\edward zion saji\appdata\local\programs\python\python36\lib\distutils\util.py", line 127, in conver
t_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'examples/Python/' cannot end with '/'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\EDWARD~1\AppData\Local\Temp\pip-install-fi9v8t6_
```
Please look into this

**Comment by Llorx** [comment]
No Windows support.
