### ISSUE TITLE
NPM error: was built for newer OSX version (10.12) than being linked (10.11)

### ISSUE THREAD

**Issue by konsumer** [Kitt-AI/snowboy#522]
OSX: 10.14.1 (18B75)
npm: 6.4.1
node: 10.9.0
node-gyp: 3.8.0

When I run `npm i snowboy`, I get a bunch of these errors:

```
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.

> speaker@0.3.1 install <LOCATION>/node_modules/speaker
> node-gyp rebuild

  CC(target) Release/obj.target/output/deps/mpg123/src/output/coreaudio.o
  LIBTOOL-STATIC Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:80:19: warning: 'Call' is deprecated
      [-Wdeprecated-declarations]
  wreq->callback->Call(1, argv);
                  ^
../../nan/nan.h:1654:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:106:8: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  Nan::ForceSet(target,
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:109:8: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  Nan::ForceSet(target,
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:112:8: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  Nan::ForceSet(target,
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:115:8: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  Nan::ForceSet(target,
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:126:8: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  Nan::ForceSet(target, Nan::New("formats").ToLocalChecked(), Nan::New(a...
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:136:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_FLOAT_32);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:137:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_FLOAT_64);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:138:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_SIGNED_8);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:139:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_UNSIGNED_8);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:140:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_SIGNED_16);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:141:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_UNSIGNED_16);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:142:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_SIGNED_24);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:143:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_UNSIGNED_24);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:144:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_SIGNED_32);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:145:3: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  CONST_INT(MPG123_ENC_UNSIGNED_32);
  ^
../src/binding.cc:133:8: note: expanded from macro 'CONST_INT'
  Nan::ForceSet(target, Nan::New(#value).ToLocalChecked(), Nan::New(value), \
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked
      deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
16 warnings generated.
  SOLINK_MODULE(target) Release/binding.node

> deepspeech@0.3.0 install <LOCATION>/node_modules/deepspeech
> node-pre-gyp install --fallback-to-build

[deepspeech] Success: "<LOCATION>/node_modules/deepspeech/lib/binding/v0.3.0/darwin-x64/node-v64/deepspeech.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> snowboy@1.3.1 install <LOCATION>/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
sed: ./Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw: No such file or directory
  SOLINK_MODULE(target) Release/snowboy.node
rm: ./Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw: No such file or directory
make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64/snowboy.node" "--module_name=snowboy" "--module_path=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd <LOCATION>/node_modules/snowboy
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64/snowboy.node --module_name=snowboy --module_path=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (<LOCATION>/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "<LOCATION>/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd <LOCATION>/node_modules/snowboy
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64/snowboy.node --module_name=snowboy --module_path=<LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64' (1)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-detect.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(matrix-wrapper.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(pipeline-vad.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-debug.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(pipeline-detect.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(audio-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(mfcc-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(nnet-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(vector-wrapper.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-io.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-utils.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(framer-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-options.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(frontend-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(vad-state-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(eavesdrop-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(intercept-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(raw-nnet-vad-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(gain-control-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(raw-energy-vad-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(license-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(template-detect-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(universal-detect-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(pipeline-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(fft-stream.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(agc.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(ns3.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(dtw-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(feat-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(srfft.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(template-container.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(snowboy-math.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(nnet-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(vad-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(analog_agc.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(noise_suppression_x.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(nnet-component.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(tdereverb_x.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(digital_agc.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(nsx_core.o)) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (<LOCATION>/node_modules/snowboy/lib/osx/libsnowboy-detect.a(frontend-lib.o)) was built for newer OSX version (10.12) than being linked (10.11)
  COPY <LOCATION>/node_modules/snowboy/lib/node/binding/Release/node-v64-darwin-x64/snowboy.node
  TOUCH Release/obj.target/action_after_build.stampboy@1.3.1~install: Failed to

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/konsumer/.npm/_logs/2018-11-13T20_19_31_001Z-debug.log
```

**Comment by hassellof** [comment]
I get the same issue

**Comment by maissani** [comment]
# NAN Update needed - Break on node 10.13
## What is the error. 
This error is related to : 

https://github.com/nodejs/nan/issues/504#issuecomment-385296082
& the same as 
https://github.com/mattermost/mattermost-server/issues/8708

It's because NAN ForceSet & other stuff like that has been deprecated / removed from Node
The newer version of NAN has been updated to handle this kind of problem.

## How you could fix this

First update NAN in your package.json & republish the node package.
Prevent this error to appear again by providing prebuilt package: @
https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-darwin-x64.tar.gz
Like in precedent releases. 
-> 
https://github.com/nodejs/nan


## How is it important to be done fast

Snowboy has a lot of dependent like Sonus / L.I.S.A Project & more... 

Because the current LTS is : 10.13.0 & Snowboy won't work with this version. 

Cordialy.

**Comment by WoodySlum** [comment]
I meet also this issue. Tried to fork project and changing `nan` dependency version and set git repo in `package.json` without success. Any help is welcome.

```
{
  "name": "testnode",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "nan": "2.11.1",
    "snowboy": "WoodySlum/snowboy"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
