### ISSUE TITLE
Snowboy - electron-v2.0-linux-arm - Error

### ISSUE THREAD

**Issue by ToxicWaste95** [Kitt-AI/snowboy#535]
Posted this in awesome-alexa and was suggested I post it here.

At my wits end with this one.. I dont have a mic or speaker connected.
the folder does not exist electron-v2.0-linux-arm, I just cannot get this installed.

Folder contents..
~/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node
/binding/Release $
total 20
drwxr-xr-x 2 pi pi 4096 May 2 2017 node-v46-darwin-x64
drwxr-xr-x 2 pi pi 4096 Feb 17 2017 node-v47-darwin-x64
drwxr-xr-x 2 pi pi 4096 Feb 17 2017 node-v48-darwin-x64
drwxr-xr-x 2 pi pi 4096 Dec 15 11:19 node-v48-linux-arm
drwxr-xr-x 2 pi pi 4096 May 2 2017 node-v51-darwin-x64
Error...

    magicmirror@2.5.0 start /home/pi/MagicMirror
    sh run-start.sh

Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-NOAA3
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-NOAA3
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
at Module._resolveFilename (module.js:543:15)
at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
at Function.Module._load (module.js:473:25)
at Module.require (module.js:586:17)
at require (internal/module.js:11:18)
at Object. (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
at Object. (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
at Module._compile (module.js:642:30)
at Object.Module._extensions..js (module.js:653:10)
at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
at Module._resolveFilename (module.js:543:15)
at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
at Function.Module._load (module.js:473:25)
at Module.require (module.js:586:17)
at require (internal/module.js:11:18)
at Object. (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
at Object. (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
at Module._compile (module.js:642:30)
at Object.Module._extensions..js (module.js:653:10)
at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }

**Comment by dnalyalp** [comment]
Hi, had the same problem and came up with a solution you can find in another module. Since this was one of this first links in google, I would like to share for others.

[https://github.com/eouia/MMM-Hotword](https://github.com/eouia/MMM-Hotword)

> But maybe in kiosk mode, you may meet some error like this;
> 
> Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
> In that case, you need to rebuild some binaries to match with Electron version.
> 
> cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> npm install --save-dev electron-rebuild
> npm install nan
> ./node_modules/.bin/electron-rebuild   # It could takes dozens sec.

**Comment by evancohen** [comment]
Electron rebuild is certainly a workable solution, however that potentially requires you to build Snowboy twice (depending on if there are binaries on AWS). My suggestion would be to set your environmental config in `.npmrc`. Check out this really simple Boilerplate for an example:  
https://github.com/evancohen/sonus-electron-boilerplate
