### ISSUE TITLE
AssertionError: number of hotwords in decoder_model (4) and sensitivity (3) does                                                                   not match

### ISSUE THREAD

**Issue by snowboy4** [Kitt-AI/snowboy#573]
```
Traceback (most recent call last):
  File "knur.py.41", line 28, in <module>
    detector = snowboydecoder_arecord.HotwordDetector(models, sensitivity=sensit                                                                  ivity)
  File "/home/pi/snowboy2/examples/Python/snowboydecoder_arecord.py", line 86, i                                                                  n _init_
    "(%d) does not match" % (self.num_hotwords, len(sensitivity))
AssertionError: number of hotwords in decoder_model (4) and sensitivity (3) does                                                                   not match
```

Hi, I got this error while I tried to implement  	neoya.umdl over snowboy.umdl and I have no idea why counting screws up and spits this error.

**Comment by haemi** [comment]
did you find a solution for this?
