### ISSUE TITLE
 Error: Cannot find module './snowboy/lib/node/index.js

### ISSUE THREAD

**Issue by pandora0309** [Kitt-AI/snowboy#587]
I don't know much about this error.
`WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
`

**Comment by evancohen** [comment]
Can you describe what you did to get into this state? Did you install via `npm`? Did you clone the repo?

**Comment by pandora0309** [comment]
When I run the smart mirror, the screen doesn't open, and those errors come out.

**Comment by evancohen** [comment]
Please close this issue and create a new one in the smart-mirror repository. I don't believe this is a Snowboy related issue.

**Comment by pandora0309** [comment]
thanks

**Comment by jazx** [comment]
i have same problem

Only ussing snowboy. There are a solution?
