### ISSUE TITLE
can't install snowboy with node

### ISSUE THREAD

**Issue by 3l0w** [Kitt-AI/snowboy#589]
When i do `npm i ` node don't install snowboy and i get some errors
node -v 10.16.0
npm -v 6.9.0
debug logs:
[2019-06-08T07_12_32_791Z-debug.log](https://github.com/Kitt-AI/snowboy/files/3268293/2019-06-08T07_12_32_791Z-debug.log)

logs :
 ```
> snowboy@1.2.0 preinstall /root/speechbot/node_modules/snowboy
> npm install node-pre-gyp

npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.39
added 112 packages from 77 contributors, updated 1 package and audited 268 packages in 5.02s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> lzma-native@3.0.8 install /root/speechbot/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

[lzma-native] Success: "/root/speechbot/node_modules/lzma-native/binding-v3.0.8-node-v64-linux-x64/lzma_native.node" is installed via remote

> ref@1.3.5 install /root/speechbot/node_modules/ref
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/speechbot/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReadPointer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:253:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   size_t size = info[2]->Uint32Value();
                                      ^
In file included from /root/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/root/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:360:30: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value _str(in);
                              ^
In file included from /root/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/root/.node-gyp/10.16.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteUInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:447:30: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value _str(in);
                              ^
In file included from /root/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/root/.node-gyp/10.16.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:521:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   size_t size = info[1]->Uint32Value();
                                      ^
In file included from /root/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/root/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBufferUntilZeros(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:550:44: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   uint32_t numZeros = info[1]->Uint32Value();
                                            ^
In file included from /root/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/root/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/binding.cc:643:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
        ^~~~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:643:187: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                                                                           ^
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:644:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
        ^~~~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:644:142: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                              ^
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/root/speechbot/node_modules/ref/build'

> snowboy@1.2.0 install /root/speechbot/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/speechbot/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
make: Entering directory '/root/speechbot/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
rm: cannot remove './Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw': No such file or directory
snowboy.target.mk:109: recipe for target 'Release/obj.target/snowboy/swig/Node/snowboy.o' failed
make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1
make: Leaving directory '/root/speechbot/node_modules/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64"
gyp ERR! cwd /root/speechbot/node_modules/snowboy
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v10.16.0/bin/node /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/speechbot/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack  SOLINK_MODULE(target) Release/obj.target/snowboy.node
     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-47-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/speechbot/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/speechbot/node_modules/snowboy
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/root/.nvm/versions/node/v10.16.0/bin/node /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
sh: 0: getcwd() failed: No such file or directoryowboy@1.2.0~install: Failed to exec install script
/bin/sh: 1: cannot create ./Release/.deps/Release/obj.target/snowboy.node.d: Directory nonexistent
snowboy.target.mk:141: recipe for target 'Release/obj.target/snowboy.node' failed
make: *** [Release/obj.target/snowboy.node] Error 2
make: Leaving directory '/root/speechbot/node_modules/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/root/speechbot/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64"
gyp ERR! cwd /root/speechbot/node_modules/snowboy
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN speechbot@1.0.0 No description
npm WARN speechbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-08T07_12_32_791Z-debug.log
```

**Comment by evancohen** [comment]
Give this a shot and see if this works for you:
```
npm install snowboy@sonus
```

**Comment by 3l0w** [comment]
Thanks that work
