### ISSUE TITLE
ModuleNotFoundError: No module named '_snowboydetect'

### ISSUE THREAD

**Issue by xiaoland** [Kitt-AI/snowboy#602]
I am run it on windows, but it said cannot find the module called _snowboydetect

**Comment by xiaoland** [comment]
Traceback (most recent call last):
  File "D:/Hadream/工作结果/编程/Python/XiaolanClient3.0/auditory_center/speech_awaken/snowboy_source/snowboydetect.py", line 26, in swig_import_helper
    fp, pathname, description = imp.find_module('_snowboydetect', [dirname(__file__)])
  File "G:\Program\python-3.6\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Program\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "G:\Program\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "G:\Program\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "G:\Program\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Hadream/工作结果/编程/Python/XiaolanClient3.0/auditory_center/speech_awaken/snowboy_source/snowboydetect.py", line 36, in <module>
    _snowboydetect = swig_import_helper()
  File "D:/Hadream/工作结果/编程/Python/XiaolanClient3.0/auditory_center/speech_awaken/snowboy_source/snowboydetect.py", line 28, in swig_import_helper
    import _snowboydetect
ModuleNotFoundError: No module named '_snowboydetect'

**Comment by hongyi-h** [comment]
Hey bro, did you solve this problem? I had the same problem on Ubuntu 21.10.

**Comment by xiaoland** [comment]
> Hey bro, did you solve this problem? I had the same problem on Ubuntu 21.10.

1. check if you have installed the right version of swig
2. check if your snowboydetect_ lib is compatible with your system arch

**Comment by Joseph513shen** [comment]
> > Hey bro, did you solve this problem? I had the same problem on Ubuntu 21.10.
> 
> 1. check if you have installed the right version of swig
> 2. check if your snowboydetect_ lib is compatible with your system arch

so ，have you succeed on windows？
