### ISSUE TITLE
Support for Raspbian 10 buster

### ISSUE THREAD

**Issue by jimbotel** [Kitt-AI/snowboy#603]
I tried to install snowboy on Buster (nodejs 10) and I got this errors:

> snowboy@1.3.1 install /home/pi/.node-red/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

Any chance this can be fixed?

Thanks,

Jaime.

**Comment by mrdago** [comment]
I'm running a rpi3 with **Linux buster 4.19.68-v7+** and node **v10.16.0** and get the same error when I try to install snowboy@1.3.1:

Would be great if this could be fixed!

```gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.68-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/phas/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/phas/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/phas/node_modules/snowboy
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by PierreB49** [comment]
I'm clearly not an expert but editing the tsconfig.json file worked for me:

Change

`    "files": [
      "lib/node/index.ts",
      "lib/node/node-pre-gyp.d.ts",
      "lib/node/SnowboyDetectNative.d.ts",
      "node_modules/@types/node/index.d.ts"
    ],`

into

`    "files": [
      "lib/node/index.ts",
      "lib/node/node-pre-gyp.d.ts",
      "lib/node/SnowboyDetectNative.d.ts"
    ],`

**Comment by jimbotel** [comment]
Hi @PierreB49 ,
Thanks for your reply. A naive question:  I'm trying to install snowboy like:

```
npm install --save snowboy
```

When this fails (see the errors above), there's no code I can review (everything is deleted), so I cannot edit tsconfig.js as you suggested. 
Any hints? (apologies if this is a dumb question)

Thanks,
Jaime-

**Comment by PierreB49** [comment]
If I understand ou cannot find the tsconfig.json file in /home/pi/.node-red/node_modules/snowboy is that right ?

**Comment by jimbotel** [comment]
Hi @PierreB49 ,
Right, when the install process fails, it leaves no trace of the directory snowboy in  `/home/pi/.node-red/node_modules/`

**Comment by evancohen** [comment]
It's not official, but I've built and shared my own binaries for newer versions of node.
```
npm install snowboy@sonus
```

**Comment by jimbotel** [comment]
Hi @evancohen , that is great! This weekend I'll give it a try

Thanks!

**Comment by jimbotel** [comment]
Hi @evancohen ,
I tried it and it installed fine for me!  
I had to do some hacking to install node-red-contrib-snowboy node in node-red, though, which is what I will be using eventually, but other than that it's working.
Thanks!
Jaime-
