### ISSUE TITLE
Demo gives error when used via crontab, works otherwise

### ISSUE THREAD

**Issue by pmishev** [Kitt-AI/snowboy#613]
When I run the demo from the terminal I get some errors, but everything works despite of that:
```
python /home/pi/snowboy/examples/Python3/demo.py /home/pi/snowboy/resources/models/snowboy.umdl
```
```
Listening... Press Ctrl+C to exit
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
```

However when I run the same thing via cron job:
```
* * * * * python /home/pi/snowboy/examples/Python3/demo.py /home/pi/snowboy/resources/models/snowboy.umdl >> /tmp/demo.log 2>&1
```
...in the log I get:
```
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Listening... Press Ctrl+C to exit
Traceback (most recent call last):
  File "/home/pi/snowboy/examples/Python3/demo.py", line 33, in <module>
    sleep_time=0.03)
  File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/home/pi/.virtualenvs/ledalert/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/.virtualenvs/ledalert/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate
```

What could possibly be different? The crontab also runs as the `pi` user.

**Comment by pmishev** [comment]
I've previously had a similar problem where a python script playing sound using `pydub.playback` wouldn't work via crontab and I solved that by prefixing the command with `XDG_RUNTIME_DIR=/run/user/1000 &&`. However that doesn't work in this situation.

**Comment by pmishev** [comment]
Ok, finally solved this. Apparently it was an underlying problem with pulse audio.
Needed to prefix the command in the crontab with `export DISPLAY=:0 &&` 

https://forums.fedoraforum.org/showthread.php?294023-Using-cron-and-ogg123-as-an-alarmclock-(possibly-again)&s=d0a0f73b11230e6a55df8bec1b1e3277&p=1669177#post1669177
