### ISSUE TITLE
Problems with cp_snowboydetect.so execution

### ISSUE THREAD

**Issue by epeiuss** [Kitt-AI/snowboy#615]
The following error reporting prompts occurred:
Bash: There is a grammatical error near the unexpected symbol "newline"
If it runs directly (in wukong), it will appear:

```
Traceback (most recent call last):
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snowboy._snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'
```

Running Environment: Raspberry Pi 3B+, rasbian System

Thank you!

**Comment by shiboli123** [comment]
请问你的问题解决了吗？我也遇到了相同的问题

**Comment by zhangxiaopang-mr** [comment]
请问你的问题解决了吗？我也遇到了相同的问题
