### ISSUE TITLE
alsa error with mic input

### ISSUE THREAD

**Issue by Ealuthwala** [Kitt-AI/snowboy#619]
```
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "hot.py", line 5, in <module>
    detector.start(detected_callback)
  File "/home/pi/Documents/voice_id/snowboydecoder.py", line 182, in start
    stream_callback=audio_callback)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate
```

this is the full error i get.

now i have added the `~/.asoundrc` file as in the docs and tested mic using `rec -r 16000 -c 1 -b 16 -e signed-integer -t wav test.wav`

i tried with two different pi still no difference. how can i fix this.

this might be an alsa error, but i still dont know how to fix it. so please help me. thanks

**Comment by IanSMoyes** [comment]
Yep, I'm suffering the same issue.

However "rec -r 16000 -c 1 -b 16 -e signed-integer -t wav test.wav" gives me "bash: rec: command not found".
