### ISSUE TITLE
snowboy install error on windows 10

### ISSUE THREAD

**Issue by Turkmen48** [Kitt-AI/snowboy#660]
#Error while using 'pip' to install snow boy. Windows 10 input to command prompt pip install snowboy Error
`(kurs) C:\Users\Turkmen\Desktop\isil>pip install snowboy
Collecting snowboy
  Using cached https://files.pythonhosted.org/packages/86/fc/3a13408cb3b32abff1b0539f44fca02ca378d9077b11f0c95674f278f
3de/snowboy-1.2.0b1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "", line 1, in 
      File "C:\Users\Turkmen\AppData\Local\Temp\pip-install-gifo0vzi\snowboy\setup.py", line 45, in 
        packages=find_packages('examples/Python/'),
      File "C:\Anaconda3\envs\kurs\lib\site-packages\setuptools\__init__.py", line 71, in find
        convert_path(where),
      File "C:\Anaconda3\envs\kurs\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'examples/Python/' cannot end with '/'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Turkmen\AppData\Local\Temp\pip-install-gifo0vzi\snowboy\`

**Comment by Zyno1x** [comment]
snowboy does not work on windows
