### ISSUE TITLE
Did you change `examples/Python/snowboydetect.py` by any chance? That file was generated by swig automatically and the first line is not `../../swig/Python/snowboydetect.py`. Your error message seems to suggest that the first line is `../../swig/Python/snowboydetect.py`

### ISSUE THREAD

**Issue by TomZhang1124** [Kitt-AI/snowboy#709]
Did you change `examples/Python/snowboydetect.py` by any chance? That file was generated by swig automatically and the first line is not `../../swig/Python/snowboydetect.py`. Your error message seems to suggest that the first line is `../../swig/Python/snowboydetect.py`

_Originally posted by @chenguoguo in https://github.com/Kitt-AI/snowboy/issues/266#issuecomment-326811309_

**Comment by TomZhang1124** [comment]
Brother, my device is the orange pie 5ubuntu20.0.04. When I ran demo, the syntax error was prompted. I tried all kinds of methods, but the problem was the same. I come from China, my English is not very good, I did not understand the solution, please help me to see, thank you. Brother, my device is orange pie 5Ubuntu 20.0.04, go to run demo
orangepi@orangepi5:/usr/src/snowboy/examples/Python3$ python3.8 demo.py resources/models/snowboy.umdl
Traceback (most recent call last):
File "demo.py", line 1, in
import snowboydecoder
File "/usr/src/snowboy/examples/Python3/snowboydecoder.py", line 5, in
import snowboydetect
File "/usr/src/snowboy/examples/Python3/snowboydetect.py", line 1
../../swig/Python3/snowboydetect.py
^
SyntaxError: invalid syntax

resources and other files in this example /Python3 seem to be redirects. My environment doesn't seem to be able to parse this

**Comment by PKUHaoWang** [comment]
请问你解决这个问题了吗，我也遇到了相同的问题
