### ISSUE TITLE
TypeError: SnowboyDetectNative is not a function

### ISSUE THREAD

**Issue by kermit-kr** [Kitt-AI/snowboy#90]
TypeError: SnowboyDetectNative is not a function
    at new SnowboyDetect (/home/pi/smart-mirror/node_modules/sonus/node_modules/snowboy/lib/node/index.js:78:31)
    at Object.CloudSpeechRecognizer.init.CloudSpeechRecognizer.startStreaming.recognitionStream.on.Sonus.init.opts.hotwords.forEach.detector.on.csr.on.csr.on [as init] (/home/pi/smart-mirror/node_modules/sonus/index.js:82:37)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:18:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

I am making a smart mirror.
Snowboy error in speech recognition

I do not know what the problem is.

**Comment by chenguoguo** [comment]
It will be more efficient if you post the issue at the smart-mirror page: https://github.com/evancohen/smart-mirror

I assume you were using Evan's smart-mirror.

**Comment by kermit-kr** [comment]
The problem was caused by the low node.js version that was fixed by viewing the link.

Thank you!
